channels:
  - conda-forge
  - usgs-astrogeology
 
dependencies:
  - cmake
  - cpp-filesystem
  - cspice=67
  - cxx-compiler
  - doxygen
  - h5py
  - highfive==2.10.1
  - fmt==9.1.0
  - libhiredis
  - ninja
  - pip
  - pytest
  - python
  - swig
  - jsonschema
  - cereal
  - spdlog
  # API dependencies
  - fastapi
  - pydantic==2.6.3
  - uvicorn
  - numpy
  - pip:
    - mkdocs 
    - mkdocs-swagger-ui-tag
    - mkdoxy
    - check-jsonschema
    - mkdocs-material
